In [1]:
import numpy as np
from scipy.linalg import solve
from scipy.linalg import inv

# Zadanie 4

In [2]:
A = np.array([[0, 0, 2, 1, 2],
              [0, 1, 0, 2, -1],
              [1, 2, 0, -2, 0],
              [0, 0, 0, -1, 1],
              [0, 1, -1, 1, -1]])

b = np.array([1, 1, -4, -2, -1])


In [3]:
def gauss_elimination_with_partial_pivoting(A, b):
    # Tworzymy kopie macierzy A i wektora b, aby nie zmieniać oryginałów
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    
    # Eliminacja w przód z częściowym wyborem elementu głównego
    for i in range(n):
        # Znajdź wiersz z największym elementem w kolumnie i zamień go z bieżącym wierszem
        max_row = np.argmax(abs(A[i:n, i])) + i
        if A[max_row, i] == 0:
            raise ValueError("Nie ma jednoznacznego rowiązania!")  # Jeśli wartość główna jest zerem, macierz nie jest odwracalna
        A[[i, max_row]] = A[[max_row, i]]  # Zamiana wierszy w macierzy A
        b[[i, max_row]] = b[[max_row, i]]  # Zamiana wierszy w wektorze b

        # Eliminacja wszystkich elementów poniżej elementu głównego
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]  # Wyliczenie współczynnika do eliminacji
            A[j, i:] -= factor * A[i, i:]  # Odejmowanie wiersza i od wiersza j, aby wyeliminować element A[j, i]
            b[j] -= factor * b[i]  # Aktualizacja wartości wektora b

    # Podstawienie wstecz 
    x = np.zeros(n)  # Inicjalizacja wektora wynikowego x zerami
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]  # Obliczenie wartości x[i]

    return x


x_gauss = gauss_elimination_with_partial_pivoting(A, b)
x_gauss



array([ 2., -2.,  1.,  1., -1.])

In [4]:
x_scipy = solve(A, b)
x_scipy

array([ 2., -2.,  1.,  1., -1.])

# Zadanie 5

In [7]:
A_poly = np.array([[1, 0, 0, 0, 0],
                   [1, 1, 1, 1, 1],
                   [1, 3, 9, 27, 81],
                   [1, 5, 25, 125, 625],
                   [1, 6, 36, 216, 1296]])

b_poly = np.array([-1, 1, 3, 2, -2])

# Teraz możesz użyć swojego algorytmu eliminacji Gaussa
coefficients = gauss_elimination_with_partial_pivoting(A_poly, b_poly)
print(coefficients)


[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


In [9]:
x_scipy = solve(A_poly, b_poly)
x_scipy

array([-1.        ,  2.68333333, -0.875     ,  0.21666667, -0.025     ])

# Zadanie 6

In [28]:
A_6 = np.array([[3.50, 2.77, -0.76, 1.80],
                [-1.80, 2.68, 3.44, -0.09],
                [0.27, 5.07, 6.90, 1.61],
                [1.71, 5.45, 2.68, 1.71]])

b_6 = np.array([7.31, 4.23, 13.85, 11.55])
det_A_6 = np.linalg.det(A_6)
x6 = gauss_elimination_with_partial_pivoting(A_6, b_6)
x6,det_A_6

(array([1., 1., 1., 1.]), np.float64(-0.2257973399999901))

In [12]:
x_scipy = solve(A_6, b_6)
x_scipy

array([1., 1., 1., 1.])

# Zadanie 7

In [13]:

A_7 = np.array([[10, -2, -1, 2, 3, 1, -4, 7],
                [5, 11, 3, 10, -3, 3, 3, -4],
                [7, 12, 1, 5, 3, -12, 2, 3],
                [8, 7, -2, 1, 3, 2, 2, 4],
                [2, -15, -1, 1, 4, -1, 8, 3],
                [4, 2, 9, 1, 12, -1, 4, 1],
                [-1, 4, -7, -1, 1, 1, -1, -3],
                [-1, 3, 4, 1, 3, -4, 7, 6]])

b_7 = np.array([0, 12, -5, 3, -25, -26, 9, -7])


x_7 = gauss_elimination_with_partial_pivoting(A_7, b_7)
x_7


array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.])

In [14]:
x_scipy = solve(A_7, b_7)
x_scipy

array([-1.,  1., -1.,  1., -1.,  1., -1.,  1.])

# Zadanie 8

In [4]:
def gauss_jordan_inverse(A):
    n = len(A)
    A = A.astype(float)  # Przekształcenie macierzy A do formatu zmiennoprzecinkowego
    
    # Tworzenie rozszerzonej macierzy [A | I]
    I = np.eye(n)  # Macierz jednostkowa o wymiarze n x n
    augmented_matrix = np.hstack((A, I))  # Łączenie macierzy A i I w jedną macierz rozszerzoną
    
    # Przeprowadzanie eliminacji Gaussa-Jordana
    for i in range(n):
        # Znalezienie elementu głównego i ewentualna zamiana wierszy
        max_row = np.argmax(abs(augmented_matrix[i:, i])) + i  # Znalezienie wiersza z największym elementem w kolumnie i
        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]  # Zamiana bieżącego wiersza z wierszem zawierającym największy element

        # Normalizacja wiersza głównego
        pivot = augmented_matrix[i, i]  # Wybór elementu głównego (pivot)
        augmented_matrix[i] = augmented_matrix[i] / pivot  # Podzielenie całego wiersza przez element główny, aby element główny stał się równy 1

        # Eliminacja bieżącej kolumny we wszystkich wierszach poza wierszem głównym
        for j in range(n):
            if j != i:
                factor = augmented_matrix[j, i]  # Współczynnik eliminacji
                augmented_matrix[j] -= factor * augmented_matrix[i]  # Eliminacja elementu w kolumnie i w wierszu j
    
    # Prawa strona rozszerzonej macierzy jest teraz odwrotnością macierzy A
    A_inv = augmented_matrix[:, n:]  # Wyciągnięcie prawej strony rozszerzonej macierzy
    return A_inv

In [5]:
A_8 = np.array([[2, -1, 0, 0, 0, 0],
                [-1, 2, -1, 0, 0, 0],
                [0, -1, 2, -1, 0, 0],
                [0, 0, -1, 2, -1, 0],
                [0, 0, 0, -1, 2, -1],
                [0, 0, 0, 0, -1, 5]])


A_inv_8 = gauss_jordan_inverse(A_8)
A_inv_8

array([[0.84, 0.68, 0.52, 0.36, 0.2 , 0.04],
       [0.68, 1.36, 1.04, 0.72, 0.4 , 0.08],
       [0.52, 1.04, 1.56, 1.08, 0.6 , 0.12],
       [0.36, 0.72, 1.08, 1.44, 0.8 , 0.16],
       [0.2 , 0.4 , 0.6 , 0.8 , 1.  , 0.2 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24]])

In [19]:
A_inv_scipy = inv(A_8)
A_inv_scipy

array([[0.84, 0.68, 0.52, 0.36, 0.2 , 0.04],
       [0.68, 1.36, 1.04, 0.72, 0.4 , 0.08],
       [0.52, 1.04, 1.56, 1.08, 0.6 , 0.12],
       [0.36, 0.72, 1.08, 1.44, 0.8 , 0.16],
       [0.2 , 0.4 , 0.6 , 0.8 , 1.  , 0.2 ],
       [0.04, 0.08, 0.12, 0.16, 0.2 , 0.24]])

Macierz $A^{-1}$ jest symetryczna, lecz nie jest trójdiagonalna. Oznacza to, że macierz odwrotna do macierzy trójdiagonalnej nie musi być macierzą trójdiagonalną. 

# Zadanie 9

In [20]:
A_9 = np.array([[1, 3, -9, 6, 4],
                [2, -1, 6, 7, 1],
                [3, 2, -3, 15, 5],
                [8, -1, 1, 4, 2],
                [11, 1, -2, 18, 7]])

A_inv_9 = gauss_jordan_inverse(A_9)
A_inv_9

array([[-2.22649869e+15, -2.22649869e+15, -2.22649869e+15,
        -4.45299738e+15,  4.45299738e+15],
       [-1.05758688e+16, -1.05758688e+16, -1.05758688e+16,
        -2.11517376e+16,  2.11517376e+16],
       [-1.77107851e+15, -1.77107851e+15, -1.77107851e+15,
        -3.54215701e+15,  3.54215701e+15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00, -1.00000000e+00],
       [ 4.50359963e+15,  4.50359963e+15,  4.50359963e+15,
         9.00719925e+15, -9.00719925e+15]])

In [21]:
A_inv_scipy = inv(A_9)
A_inv_scipy

array([[-2.22649869e+15, -2.22649869e+15, -2.22649869e+15,
        -4.45299738e+15,  4.45299738e+15],
       [-1.05758688e+16, -1.05758688e+16, -1.05758688e+16,
        -2.11517376e+16,  2.11517376e+16],
       [-1.77107851e+15, -1.77107851e+15, -1.77107851e+15,
        -3.54215701e+15,  3.54215701e+15],
       [-1.11022302e-16, -0.00000000e+00,  1.00000000e+00,
         1.00000000e+00, -1.00000000e+00],
       [ 4.50359963e+15,  4.50359963e+15,  4.50359963e+15,
         9.00719925e+15, -9.00719925e+15]])



Rozwiązanie w tym zadaniu nie jest poprawne, ponieważ niedokładność w zapisywaniu wartości przez komputer, powoduje, że program nie uzyskuje dokładnego  wyniku wyznacznika, czyli 0, lecz liczbę bardzo bliską tej wartości. Powoduje to błędne wyliczenie macierzy odwrotnej, która dla tego konkretnego przypadku nie istnieje, ponieważ macierz A jest osobliwa.
